import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { UseRedPacket } from "@/hooks/useRedPacket";
import { useState } from 'react';

function Home() {
  const {
    balance,
    isBalanceLoading,
    isBalanceError,
    deposit,
  } = UseRedPacket();
  const [amount, setAmount] = useState(0);
  const type: string = typeof balance;
  console.log("balance type:", type, "balance:", balance);
  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <ConnectButton />

        <div>
          {isBalanceLoading && <p>Loading balance...</p>}
          {isBalanceError && <p>Error loading balance</p>}
          {balance ? <p>Contract Balance:{ } {(Number(balance) / 1e18)} ETH</p> : <p>0 ETH</p>}
        </div>
        <div>
          <h1 className="text-3xl font-bold underline">
            Hello world!
          </h1>
          <Input value={amount} onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
            setAmount(Number(e.target.value));
          }} type="text" />
          <Button onClick={() => { deposit(BigInt(amount)) }}>充值</Button>
        </div>
      </main>
    </div>
  );
};

export default Home;