import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import { Abi } from 'viem'
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useReadContract, UseReadContractParameters,UseReadContractReturnType  } from 'wagmi'
import RedPacketABI from '../abi/AssignRedPacket.json'
const ContractConfig: Pick<UseReadContractParameters, 'address' | 'abi'> = {
  address: '0x54c1Bd6df115Aa06Dde30EFb3b179F1e61b6e37a',
  abi: RedPacketABI.abi as Abi
}
const Home: NextPage = () => {
  const result:UseReadContractReturnType = useReadContract({
    ...ContractConfig,
    functionName: 'getBalance'
  })
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <div>
          {result.isLoading && <p>Loading balance...</p>}
          {result.isError && <p>Error loading balance</p>}
          {result.data && <p>Balance: {Number(result.data) / 1e18} ETH</p>}
        </div>
      </main>
    </div>
  );
};

export default Home;
